version: "3.1"
services:
  app:
    container_name: log-server
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    restart:  always
    ports:
    - "9010:80"
    volumes:
    - ./src:/var/www/html
    env_file:
        - ./environment/.env-app
    environment:
        - DEPLOY_TYPE="dev"
  database:
    container_name: log-db
    image: mysql:5.7
    volumes:
        - dbdata:/var/lib/mysql
    env_file:
        - ./environment/.env-docker
    ports:
        - "33061:3306"
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/var/lib/redis
volumes:
  dbdata:
  redisdata:
